# Trigger builds for only pushes to some branches
trigger:
  branches:
    include:
    - main
    - release/*

# Trigger builds for PRs to any branch
pr:
  branches:
    include:
    - '*'

schedules:
- cron: 0 9 * * 1
  displayName: "Run CodeQL3000 weekly, Monday at 2:00 AM PDT"
  branches:
    include:
    - release/2.1
    - main
  always: true

parameters:
# Parameters below are ignored in public builds.
#
# Choose whether to run the CodeQL3000 tasks.
# Manual builds align w/ official builds unless this parameter is true.
- name: runCodeQL3000
  default: false
  displayName: Run CodeQL3000 tasks
  type: boolean

variables:
  BuildConfiguration: Release

jobs:
- template: jobs/project-ci.yml
  parameters:
    # Ensures the alignment of branch name and deployment params
    buildArgs: '/warnaserror:BUILD1001'
    ${{ if and(eq(variables['System.TeamProject'], 'internal'), or(eq(variables['Build.Reason'], 'Schedule'), and(eq(variables['Build.Reason'], 'Manual'), eq(parameters.runCodeQL3000, 'true')))) }}:
      runCodeQL3000: true
    ${{ else }}:
      afterBuild:
      - task: PublishBuildArtifacts@1
        displayName: Upload KoreBuild artifact
        condition: and(succeeded(), eq(variables['BuildConfiguration'], 'Release'), eq(variables['AgentOsName'], 'Windows'), eq(variables['system.pullrequest.isfork'], false))
        inputs:
          pathtoPublish: artifacts/korebuild/
          artifactName: korebuild
          artifactType: Container
