# Trigger builds for only pushes to some branches
trigger:
  branches:
    include:
    - master
    - release/*

# Trigger builds for PRs to any branch
pr:
  branches:
    include:
    - '*'

jobs:
- job: Ubuntu_16_04
  displayName: Ubuntu-16.04
  workspace:
    clean: all
  pool:
    vmImage: ubuntu-16.04
  steps:
  - bash: locale
    displayName: 'Show locale'
- job: Ubuntu_18_04
  displayName: Ubuntu-18.04
  workspace:
    clean: all
  pool:
    vmImage: ubuntu-18.04
  steps:
  - bash: locale
    displayName: 'Show locale'
  - bash: locale
    continueOnError: true
    displayName: 'Show locale with environment'
    env:
      LC_ALL: 'en_US.UTF-8'
      LANG: 'en_US.UTF-8'
      LANGUAGE: 'en_US.UTF-8'
  - bash: |
      locale-gen 'en_US.UTF-8'
      locale
    condition: always()
    continueOnError: true
    displayName: 'Show locale with locale-gen'
    env:
      LC_ALL: 'en_US.UTF-8'
      LANG: 'en_US.UTF-8'
      LANGUAGE: 'en_US.UTF-8'
  - bash: |
      sudo locale-gen 'en_US.UTF-8'
      locale
    condition: always()
    continueOnError: true
    displayName: 'Show locale with sudo locale-gen'
    env:
      LC_ALL: 'en_US.UTF-8'
      LANG: 'en_US.UTF-8'
      LANGUAGE: 'en_US.UTF-8'
