# Trigger builds for only pushes to some branches
trigger:
  branches:
    include:
    - main
    - release/*

# Trigger builds for PRs to any branch
pr:
  branches:
    include:
    - '*'

resources:
  repositories:
  # Repo: 1ESPipelineTemplates/1ESPipelineTemplates
  - repository: 1esPipelines
    type: git
    name: 1ESPipelineTemplates/1ESPipelineTemplates
    ref: refs/tags/release

extends:
  template: v1/1ES.Official.PipelineTemplate.yml@1esPipelines
  parameters:
    sdl:
      sourceAnalysisPool:
        name: NetCore1ESPool-Svc-Internal
        image: 1es-windows-2022-pt
        os: windows
    stages:
    - stage: build
      displayName: Build
      jobs:
      - template: .azure/templates/project-ci.yml@self
        parameters:
          # Ensures the alignment of branch name and deployment params
          buildArgs: '/warnaserror:BUILD1001'
          afterBuild:
          - task: 1ES.PublishPipelineArtifact@1
            displayName: Upload KoreBuild artifact
            condition: and(succeeded(), eq(variables['BuildConfiguration'], 'Release'), eq(variables['AgentOsName'], 'Windows'), eq(variables['system.pullrequest.isfork'], false))
            inputs:
              path: artifacts/korebuild/
              artifactName: korebuild
