language: csharp
sudo: false
services:
  - docker
dist: trusty
env:
  global:
    - DOTNET_CLI_TELEMETRY_OPTOUT: 1
mono: none
addons:
  apt:
    packages:
      - libunwind8
branches:
  only:
    - master
    - release
    - dev
    - /^rel\/.*/
    - /^(.*\/)?ci-.*$/
script:
  - ./build.sh
