# Description: Runs build.cmd/sh on macOS, Linux, and Windows
# Parameters:
#   buildArgs: string
#       Additional arguments to pass to the build.sh/cmd script.
#       Note: -ci is always passed
#   beforeBuild: [steps]
#       Additional steps to run before build.sh/cmd
#   afterBuild: [steps]
#       Additional steps to run after build.sh/cmd
#   variables: {}
#       VSTS build and environment variables
#   matrix: {}
#       The matrix of configurations to run. By default, it runs a Debug and Release build on all platforms
#   codeSign: boolean
#       This build definition is enabled for code signing. (Only applies to Windows)

parameters:
  buildArgs: ''
  beforeBuild: []
  afterBuild: []
  codeSign: false
  variables: {}
  matrix:
    Release:
      BuildConfiguration: Release
    Debug:
      BuildConfiguration: Debug

jobs:
- template: jobs/default-build.yml
  parameters:
    agentOs: Windows
    matrix: ${{ parameters.matrix }}
    buildArgs: ${{ parameters.buildArgs }}
    beforeBuild: ${{ parameters.beforeBuild }}
    afterBuild: ${{ parameters.afterBuild }}
    codeSign: ${{ parameters.codeSign }}
    variables: ${{ parameters.variables }}
- template: jobs/default-build.yml
  parameters:
    agentOs: macOS
    matrix: ${{ parameters.matrix }}
    buildArgs: ${{ parameters.buildArgs }}
    beforeBuild: ${{ parameters.beforeBuild }}
    afterBuild: ${{ parameters.afterBuild }}
    variables: ${{ parameters.variables }}
- template: jobs/default-build.yml
  parameters:
    agentOs: Linux
    matrix: ${{ parameters.matrix }}
    buildArgs: ${{ parameters.buildArgs }}
    beforeBuild: ${{ parameters.beforeBuild }}
    afterBuild: ${{ parameters.afterBuild }}
    variables: ${{ parameters.variables }}

