# Description: Runs build.cmd/sh on macOS, Linux, and Windows
# Parameters:
#   buildArgs: string
#       Additional arguments to pass to the build.sh/cmd script.
#       Note: -ci is always passed
#   beforeBuild: [steps]
#       Additional steps to run before build.sh/cmd
#   afterBuild: [steps]
#       Additional steps to run after build.sh/cmd
#   variables: {}
#       Azure DevOps build and environment variables
#   matrix: {}
#       The matrix of configurations to run. By default, it runs a Debug and Release build on all platforms
#   codeSign: boolean
#       This build definition is enabled for code signing. (Only applies to Windows)
#   runCodeQL3000: boolean
#       This build should run CodeQL3000 instead of the regular build

parameters:
  buildArgs: ''
  beforeBuild: []
  afterBuild: []
  codeSign: false
  variables: {}
  runCodeQL3000: false

jobs:
- ${{ if and(ne(variables['System.TeamProject'], 'public'), eq(parameters.runCodeQL3000, 'true')) }}:
  - template: default-build.yml
    parameters:
      agentOs: Windows
      matrix: ${{ parameters.matrix }}
      buildArgs: ${{ parameters.buildArgs }}
      beforeBuild:
      - script: "echo ##vso[build.addbuildtag]CodeQL3000"
        displayName: 'Set CI CodeQL3000 tag'
      - task: CodeQL3000Init@0
        displayName: CodeQL Initialize
      afterBuild:
      - task: CodeQL3000Finalize@0
        displayName: CodeQL Finalize
      codeSign: false
      variables:
      - name: Codeql.SourceRoot
        value: src
      - name: _AdditionalBuildArgs
        value: /p:Test=false /p:Sign=false /p:Pack=false /p:Publish=false /p:UseSharedCompilation=false
      # Security analysis is included in normal runs. Disable its auto-injection.
      - name: skipNugetSecurityAnalysis
        value: true
      # Do not let CodeQL3000 Extension gate scan frequency.
      - name: Codeql.Cadence
        value: 0
      # Enable CodeQL3000 unconditionally so it may be run on any branch.
      - name: Codeql.Enabled
        value: true
      # CodeQL3000 needs this plumbed along as a variable to enable TSA.
      - name: Codeql.TSAEnabled
        value: ${{ eq(variables['Build.Reason'], 'Schedule') }}
- ${{ else }}: # regular build
  - template: default-build.yml
    parameters:
      agentOs: Windows
      matrix: ${{ parameters.matrix }}
      buildArgs: ${{ parameters.buildArgs }}
      beforeBuild: ${{ parameters.beforeBuild }}
      afterBuild: ${{ parameters.afterBuild }}
      codeSign: ${{ parameters.codeSign }}
      variables: ${{ parameters.variables }}
  - template: default-build.yml
    parameters:
      agentOs: macOS
      matrix: ${{ parameters.matrix }}
      buildArgs: ${{ parameters.buildArgs }}
      beforeBuild: ${{ parameters.beforeBuild }}
      afterBuild: ${{ parameters.afterBuild }}
      variables: ${{ parameters.variables }}
  - template: default-build.yml
    parameters:
      agentOs: Linux
      matrix: ${{ parameters.matrix }}
      buildArgs: ${{ parameters.buildArgs }}
      beforeBuild: ${{ parameters.beforeBuild }}
      afterBuild: ${{ parameters.afterBuild }}
      variables: ${{ parameters.variables }}
