trigger:
- master
- release/*

phases:
- template: ../templates/project-ci.yml
  parameters:
    # Ensures the alignment of branch name and deployment params
    buildArgs: '/warnaserror:BUILD1001'
    afterBuild:
    - task: PublishBuildArtifacts@1
      displayName: Upload KoreBuild artifact
      condition: and(succeeded(), eq(variables['param.configuration', 'Release']), eq(variables['param.agentOs'], 'Windows'), eq(variables['system.pullrequest.isfork'], false))
      inputs:
        pathtoPublish: artifacts/korebuild/
        artifactName: korebuild
        artifactType: Container
